### PR TITLE
Doc fixes and some errors

### PR DESCRIPTION
**Pull request by muschellij2**
Still erroring but closer to a checking package.  Easy reproducible failure:
```r
library(reticulate)
library(keras)
library(ANTsRNet)
inputImageSize = c( 256L, 256L, 1L )
inputs <- layer_input( shape = inputImageSize )
outputs <- inputs %>% layer_zero_padding_2d( padding = c( 3L, 3L ) )
layer_scale = ANTsRNet:::layer_scale
outputs %>% 
	layer_scale(axis = -1L)
```

This will segfault

### CODE REVIEW

**Comment by ntustison** [comment]
Thanks @muschellij2 --- in addition to @stnava, it's about time we had someone with some professional R packaging skills give ANTsRNet a good review.  And it's actually quite timely.  I've been taken away from development due to other projects but am finally getting back to this stuff.  We're transitioning to tensorflow 2.0 and so I'll be cleaning out any remnants of a possible Theano backend.  After everything's stable, I'll start migrating everything over to tf.keras.  Anyway, again, much appreciation for all the work. 

I just quickly ran your example and I don't run into any issues:

```
> library(reticulate)
> library(keras)
Warning message:
package ‘keras’ was built under R version 3.5.2 
> library(ANTsRNet)
> inputImageSize = c( 256L, 256L, 1L )
> inputs <- layer_input( shape = inputImageSize )
outputs <- inputs %>% layer_zero_padding_2d( padding = c( 3L, 3L ) )
> outputs <- inputs %>% layer_zero_padding_2d( padding = c( 3L, 3L ) )
> layer_scale = ANTsRNet:::layer_scale
> outputs %>% 
+ layer_scale(axis = -1L)
2020-01-29 15:23:52.370665: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-29 15:23:52.428570: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fcacfa2f6c0 executing computations on platform Host. Devices:
2020-01-29 15:23:52.428603: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
>
```

**Comment by ntustison** [comment]
Great. Thanks @muschellij2 .  So is this ready to merge?

**Comment by muschellij2** [comment]
I just added a test - so once checked it can go in.  Also, `brainExtraction` model doesn't look like it loads:
``` r
library(ANTsRNet)
res= getPretrainedNetwork("brainExtraction")
testthat::expect_true(file.exists(res))
model = keras::load_model_hdf5(res)
#> Error in py_call_impl(callable, dots$args, dots$keywords): ValueError: No model found in config file.
#> 
#> Detailed traceback: 
#>   File "/Users/johnmuschelli/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
#>     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
#>   File "/Users/johnmuschelli/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 165, in load_model_from_hdf5
#>     raise ValueError('No model found in config file.')
```

<sup>Created on 2020-01-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2020-01-29                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version     date       lib source                             
#>  ANTsR         0.5.4.2     2019-11-14 [1] local                              
#>  ANTsRCore     0.7.3       2019-12-11 [1] Github (ANTsX/ANTsRCore@416d8f1)   
#>  ANTsRNet    * 1.1         2020-01-30 [1] local                              
#>  assertthat    0.2.1       2019-03-21 [1] CRAN (R 3.6.0)                     
#>  backports     1.1.5       2019-10-02 [1] CRAN (R 3.6.0)                     
#>  base64enc     0.1-3       2015-07-28 [1] CRAN (R 3.6.0)                     
#>  cli           2.0.1       2020-01-08 [1] CRAN (R 3.6.0)                     
#>  crayon        1.3.4       2017-09-16 [1] CRAN (R 3.6.0)                     
#>  digest        0.6.23      2019-11-23 [1] CRAN (R 3.6.0)                     
#>  evaluate      0.14        2019-05-28 [1] CRAN (R 3.6.0)                     
#>  fansi         0.4.1       2020-01-08 [1] CRAN (R 3.6.0)                     
#>  fs            1.3.1       2019-05-06 [1] CRAN (R 3.6.0)                     
#>  generics      0.0.2       2018-11-29 [1] CRAN (R 3.6.0)                     
#>  glue          1.3.1       2019-03-12 [1] CRAN (R 3.6.0)                     
#>  highr         0.8         2019-03-20 [1] CRAN (R 3.6.0)                     
#>  htmltools     0.4.0       2019-10-04 [1] CRAN (R 3.6.0)                     
#>  ITKR          0.5.2       2019-11-05 [1] Github (stnava/ITKR@fe97efa)       
#>  jsonlite      1.6         2018-12-07 [1] CRAN (R 3.6.0)                     
#>  keras         2.2.5.0     2019-10-08 [1] CRAN (R 3.6.0)                     
#>  knitr         1.26.1      2020-01-05 [1] Github (muschellij2/knitr@f5af631) 
#>  lattice       0.20-38     2018-11-04 [1] CRAN (R 3.6.0)                     
#>  magrittr      1.5         2014-11-22 [1] CRAN (R 3.6.0)                     
#>  Matrix        1.2-17      2019-03-22 [1] CRAN (R 3.6.0)                     
#>  mvtnorm       1.0-11      2019-06-19 [1] CRAN (R 3.6.0)                     
#>  pillar        1.4.3       2019-12-20 [1] CRAN (R 3.6.0)                     
#>  pkgconfig     2.0.3       2019-09-22 [1] CRAN (R 3.6.0)                     
#>  purrr         0.3.3       2019-10-18 [1] CRAN (R 3.6.0)                     
#>  R6            2.4.1       2019-11-12 [1] CRAN (R 3.6.0)                     
#>  Rcpp          1.0.3       2019-11-08 [1] CRAN (R 3.6.0)                     
#>  RcppEigen     0.3.3.7.0   2019-11-16 [1] CRAN (R 3.6.0)                     
#>  reprex        0.3.0.9001  2020-01-05 [1] Github (tidyverse/reprex@5ae0b29)  
#>  reticulate    1.13        2019-07-24 [1] CRAN (R 3.6.0)                     
#>  rlang         0.4.2       2019-11-23 [1] CRAN (R 3.6.0)                     
#>  rmarkdown     2.0.7       2020-01-17 [1] Github (rstudio/rmarkdown@2faf16a) 
#>  rstudioapi    0.10.0-9003 2020-01-05 [1] Github (rstudio/rstudioapi@abe596d)
#>  sessioninfo   1.1.1       2018-11-05 [1] CRAN (R 3.6.0)                     
#>  stringi       1.4.5       2020-01-11 [1] CRAN (R 3.6.0)                     
#>  stringr       1.4.0       2019-02-10 [1] CRAN (R 3.6.0)                     
#>  styler        1.1.1       2019-05-06 [1] CRAN (R 3.6.0)                     
#>  tensorflow    2.0.0       2019-10-02 [1] CRAN (R 3.6.0)                     
#>  testthat      2.3.0       2019-11-05 [1] CRAN (R 3.6.0)                     
#>  tfruns        1.4         2018-08-25 [1] CRAN (R 3.6.0)                     
#>  tibble        2.1.3       2019-06-06 [1] CRAN (R 3.6.0)                     
#>  whisker       0.4         2019-08-28 [1] CRAN (R 3.6.0)                     
#>  withr         2.1.2       2018-03-15 [1] CRAN (R 3.6.0)                     
#>  xfun          0.11        2019-11-12 [1] CRAN (R 3.6.0)                     
#>  yaml          2.2.0       2018-07-25 [1] CRAN (R 3.6.0)                     
#>  zeallot       0.1.0       2018-01-28 [1] CRAN (R 3.6.0)                     
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by ntustison** [comment]
Hmmm, I just tried it and it downloads without a problem:

```
> res <- getPretrainedNetwork( "brainExtraction" )
trying URL 'https://ndownloader.figshare.com/files/13729661'
Content type 'application/octet-stream' length 1469520 bytes (1.4 MB)
==================================================
downloaded 1.4 MB
```

**Comment by muschellij2** [comment]
You can download - but try to load it using `keras::load_model_hdf5`

**Comment by ntustison** [comment]
Yeah, that error looks vaguely familiar and why I changed model loading to the usage [here](https://github.com/ANTsXNet/BrainExtraction/blob/master/Scripts/doBrainExtraction.R#L40-L50) which does work.

**Comment by muschellij2** [comment]
Had to zip it because GitHub can't do h5, but I made the output from your code which can be used with `load_model_hdf5`, but I think it may be less robust as you can change the input size as you did in your code:
[brainExtraction.h5.zip](https://github.com/ANTsX/ANTsRNet/files/4135028/brainExtraction.h5.zip)

Not sure if models vs. a model config (or weights?) should be separated since I'd think `load_model_hdf5` would work with pretrained models, but this isn't always the case.

**Comment by ntustison** [comment]
@muschellij2 As soon as this gets merged I'll take a look at the issues that you've raised.

**Comment by muschellij2** [comment]
Good to merge

**Comment by ntustison** [comment]
@muschellij2 It looks to be a minor text omission in the your last commit.

**Comment by muschellij2** [comment]
Yup - fixed

**Comment by ntustison** [comment]
Great.  Thanks again @muschellij2 .

**Comment by ntustison** [comment]
@muschellij2 See [here](https://github.com/ANTsX/ANTsRNet/blob/master/R/createInpaintingDeepFillModel.R).  Is there some way we can avoid these huge indentation blocks while maintaining what I presume to be are R coding standards ?

**Comment by adigherman** [comment]
John already fixed this but for future reference you can give [styler](https://styler.r-lib.org/index.html) a try. Here's  the [result](https://github.com/adigherman/ANTsRNet/blob/master/R/createInpaintingDeepFillModel.R) after running the command below.
```
> styler::style_file('R/createInpaintingDeepFillModel.R')
Styling  1  files:
 R/createInpaintingDeepFillModel.R ℹ 
────────────────────────────────────────
Status	Count	Legend 
✓ 	0	File unchanged.
ℹ 	1	File changed.
x 	0	Styling threw an error.
────────────────────────────────────────
Please review the changes carefully!
```

**Comment by ntustison** [comment]
Perfect.  Thanks @adigherman I was just about to ask that.

**Comment by muschellij2** [comment]
I tend to use formatR::tidy_file() but styler is good too for these
solutions.  I do it inside the Rstudio app directly.
Best,
John

**Pull request merged**
